<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="F_Zbm1" Id="{71033c13-fe06-4a4a-b389-be39c96f346c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Zbm1 : Real
VAR_INPUT
END_VAR
VAR
	Hm1: LREAL;
END_VAR
VAR CONSTANT
	bZm1 : REAL:=733.772//m
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Hm1 = 1400000+mr1k1 ben Y up
F_Hm1:= 1400000+M12.fPosition;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>